CREATE TABLE Customer
(
  name VARCHAR(50) NOT NULL,
  surname VARCHAR(50) NOT NULL,
  phoneNumber VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  customerID INT NOT NULL UNIQUE AUTO_INCREMENT,
  PRIMARY KEY (customerID)
);

CREATE TABLE Store
(
  storeID INT NOT NULL UNIQUE AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(500) NOT NULL,
  longitude FLOAT NOT NULL,
  latitude FLOAT NOT NULL,
  maxCustomers INT NOT NULL,
  timeOut INT NOT NULL,
  PRIMARY KEY (storeID)
);

CREATE TABLE PartnerStore
(
  partnerID INT NOT NULL UNIQUE AUTO_INCREMENT,
  primaryStoreID INT NOT NULL,
  partnerStoreID INT NOT NULL,
  PRIMARY KEY (partnerID),
  FOREIGN KEY (primaryStoreID) REFERENCES Store(storeID),
  FOREIGN KEY (partnerStoreID) REFERENCES Store(storeID)
);

CREATE TABLE WorkingHours
(
  workingHoursID INT NOT NULL UNIQUE AUTO_INCREMENT,
  startTime DATETIME NOT NULL,
  endTime DATETIME NOT NULL,
  storeID INT NOT NULL,
  FOREIGN KEY (storeID) REFERENCES Store(storeID),
  PRIMARY KEY (workingHoursID)
);

CREATE TABLE Employe
(
  employeID INT NOT NULL UNIQUE AUTO_INCREMENT,
  email VARCHAR(50) NOT NULL,
  Role VARCHAR(50) NOT NULL,
  storeID INT NOT NULL,
  PRIMARY KEY (employeID),
  FOREIGN KEY (storeID) REFERENCES Store(storeID)
);

CREATE TABLE LineNumber
(
  startTime DATETIME NOT NULL,
  endTime DATETIME NOT NULL,
  number INT NOT NULL,
  status VARCHAR(50) NOT NULL,
  lineNumberID INT NOT NULL UNIQUE AUTO_INCREMENT,
  customerID INT NOT NULL,
  storeID INT NOT NULL,
  PRIMARY KEY (lineNumberID),
  FOREIGN KEY (customerID) REFERENCES Customer(customerID),
  FOREIGN KEY (storeID) REFERENCES Store(storeID)
);
